### ISSUE TITLE
installing from anaconda

### ISSUE THREAD

**Issue by fabrizioruffini** [scikit-hep/root_pandas#35]
Dear sirs,
I'm trying to install root_pandas in my anaconda environment; so I tried this command from anaconda.org repository: 
>> conda install -c nlesc root_pandas=python3 

from https://anaconda.org/nlesc/root_pandas
Unfortunately, it fails:
 ............

Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - python 2.7*
  - root_pandas python3*
Use "conda info <package>" to see the dependencies for each package.
 ............

I have python 3.5.1 installed, so I though that using conda install -c nlesc root_pandas=python3  I would do the right action. But the conflict is about python2.7, so I do not know what to do.

I'm using a Centos machine
Linux x86_64 x86_64 GNU/Linux
where I installed ROOT 6.09/01
running anaconda 
Python 3.5.1 |Anaconda 4.1.0 (64-bit)| (default, Jun 15 2016, 15:32:45) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
with pandas.__version__ '0.18.1'

Could you please help me?
Many thanks.
F. Ruffini

**Comment by remenska** [comment]
Hi @fabrizioruffini, you should use the following instead:
```
conda install -c nlesc root_pandas python=3
```

**Comment by fabrizioruffini** [comment]
Sorry again,
I tried the new command but a new problem arise

>> conda install -c nlesc root_pandas python=3

Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - gevent-websocket -> python 2.6*|2.7*
  - root_pandas

Many thanks again
F. Ruffini

**Comment by remenska** [comment]
Hm, @fabrizioruffini I don't really know why the gevent-websocket package is there in your environment (do you need it?). That one doesn't have python 3 support.
Maybe create a separate conda environment and install root_pandas there?

**Comment by chrisburr** [comment]
@fabrizioruffini I presume this issue has been resolved. If not, reply and I will reopen the issue.

**Comment by Hosein47** [comment]
I still have the problem
$ conda install -c nlesc root_pandas python=3

Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - root_pandas

Current channels:

  - https://conda.anaconda.org/nlesc/osx-64
  - https://conda.anaconda.org/nlesc/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

**Comment by mayou36** [comment]
I would recommend you to install root from the conda-forge channel (which is a new package, the nlesc one is outdated) and install root_pandas with pip.

As an alternative and the longterm option: you may consider switching to [uproot](https://github.com/scikit-hep/uproot)
